pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'cd multi-stage-multi-agent && javac hello.java'   // ← fix
        sh 'cd multi-stage-multi-agent && java Hello'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
       sh 'node --version'
        sh 'cd multi-stage-multi-agent && node hello.js' 
      }
    }
  }
}
